include(CheckCCompilerFlag)

function(check_c_compiler_linker_flag flag out_var)
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${flag}")
  check_c_compiler_flag(${flag} ${out_var})
endfunction()

macro(add_c_compiler_flag policy name flag)
  check_c_compiler_flag(${flag} "C_SUPPORTS_${name}")
  if (C_SUPPORTS_${name})
    add_definitions(${flag})
  elseif (NOT (${policy} STREQUAL "OPTIONAL"))
    message(FATAL_ERROR "${flag} flag is not supported by ${CMAKE_C_COMPILER}")
  endif()
endmacro()

macro(add_c_compiler_linker_flag policy name flag)
  check_c_compiler_linker_flag(${flag} "C_SUPPORTS_${name}")
  if (C_SUPPORTS_${name})
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${flag}")
  elseif (NOT (${policy} STREQUAL "OPTIONAL"))
    message(FATAL_ERROR "${flag} flag is not supported by ${CMAKE_C_COMPILER}")
  endif()
endmacro()
